version: '3.8'

services:

  gr-registry:
    container_name: gr-registry
    image: registry:2
    networks:
      - gr-network
    ports:
      - 10.0.206.21:5000:5000
    volumes:
      - ${BASE}/registry:/var/lib/registry
    restart: unless-stopped

  gr-gitlab:
    depends_on:
      - gr-registry
    container_name: gr-gitlab
    hostname: gitlab.ifmt.edu.br
    image: gitlab/gitlab-ce:14.9.0-ce.0
    networks:
      - gr-network
    ports:
      - 10.0.206.21:8022:22
      - 10.0.206.21:8080:80
      - 10.0.206.21:8443:443
      - 10.0.206.21:5005:5005
    volumes:
      - ${BASE}/gitlab/etc:/etc/gitlab
      - ${BASE}/gitlab/log:/var/log/gitlab
      - ${BASE}/gitlab/opt:/var/opt/gitlab
    restart: unless-stopped

networks:

  gr-network:
    name: gr-network
    driver: bridge
