version: '3.9'

services:

  wm-mariadb:
    container_name: wm-mariadb
    environment:
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    image: bitnami/mariadb:10.7.3
    networks:
      - wm-network
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - wm-mariadb:/bitnami/mariadb

  wm-wordpress:
    container_name: wm-wordpress
    depends_on:
      - wm-mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=wm-mariadb
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    image: bitnami/wordpress:5.9.3
    networks:
      - wm-network
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
    volumes:
      - wm-wordpress:/bitnami/wordpress

  wm-phpmyadmin:
    container_name: wm-phpmyadmin
    depends_on:
      - wm-mariadb
    environment:
      - DATABASE_HOST=wm-mariadb
    image: bitnami/phpmyadmin:5.1.3
    networks:
      - wm-network
    ports:
      - 9080:8080
      - 9443:8443
    volumes:
      - wm-phpmyadmin:/bitnami/phpmyadmin
    restart: unless-stopped

networks:

  wm-network:
    name: wm-network
    driver: bridge

volumes:

  wm-mariadb:
    name: wm-mariadb
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/wordpress-mariadb/mariadb
      o: bind

  wm-wordpress:
    name: wm-wordpress
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/wordpress-mariadb/wordpress
      o: bind

  wm-phpmyadmin:
    name: wm-phpmyadmin
    driver: local
    driver_opts:
      type: none
      device: ${BASE}/wordpress-mariadb/phpmyadmin
      o: bind
